version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 15
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Toronto'
    reviewers:
      - 'OleksiiKachan'
