version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.18.2

orbs:
  node: circleci/node@4.5.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build package
          command: yarn release
      - run:
          name: Build storybook
          command: yarn build-storybook
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  deploy-package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn publish
  deploy-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish storybook
          command: curl -X POST -d {} https://api.netlify.com/build_hooks/613641c16ad27a16af671ae3

workflows:
  publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-package:
          requires:
            - build
          filters:
            branches:
              only:
                - release
      - deploy-storybook:
          requires:
            - build
          filters:
            branches:
              only:
                - release
