version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.17.5

orbs:
  node: circleci/node@4.5.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run build
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: [.]
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn publish

workflows:
  publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - release
